# Pregunta 3

Se importan las librerías y se cargan los datos

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
cc_apps = pd.read_csv("cca.csv", header=None)

Se imprime la información del dataset. Se hace la revision de valores faltantes el en dataset y se reemplaza por NaN. Se verifica de nuevo los datos faltantes

In [2]:
x = cc_apps
y = [0,1]
print(cc_apps.head())
cc_apps
print("\n")
cc_apps_info = cc_apps.info()
print(cc_apps_info)
print("\n")
cc_apps.tail(17)
print(cc_apps.isnull().values.sum())
cc_apps = cc_apps.replace("?",np.NaN)
cc_apps.tail(17)

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       690 non-null    object 
 1   1       690 non-null    object 
 2   2       690 non-null    float64
 3   3       690 non-null    object 
 4   4       690 non-null    object 
 5   5       690 non-null    object 
 6   6       690 non-null    object 
 7   7       690 non-null    float64
 8   8       690 non-null    object 
 9   9       690 non-null    object 
 10  10      690 non-null    int64  
 11 

0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
673  NaN  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674    a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675    a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676    a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677    b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678    a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679    a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680    b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681    b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682    b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683    b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684    b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685    b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686    a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687    a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688    b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689    b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

Muestra la verificación de las iteraciones por columna contando los valores Nan

In [6]:
cc_apps = cc_apps.fillna(cc_apps.mean())
print(cc_apps.isnull().values.sum())
print(cc_apps.info())

for col in cc_apps.columns:
    if cc_apps[col].dtypes == 'object':
        """Verifica si la columna es de tipo object"""
        cc_apps[col] = cc_apps[col].fillna(cc_apps[col].value_counts().index[0])
        """lo representa con el valor más frecuente"""
print(cc_apps.isnull().values.sum())

67
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       678 non-null    object 
 1   1       678 non-null    object 
 2   2       690 non-null    float64
 3   3       684 non-null    object 
 4   4       684 non-null    object 
 5   5       681 non-null    object 
 6   6       681 non-null    object 
 7   7       690 non-null    float64
 8   8       690 non-null    object 
 9   9       690 non-null    object 
 10  10      690 non-null    int64  
 11  11      690 non-null    object 
 12  12      690 non-null    object 
 13  13      677 non-null    object 
 14  14      690 non-null    int64  
 15  15      690 non-null    object 
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB
None
0


Se itera en todos los valores de cada columna y se extrae sus dtypes. Se convierte el dataset en una matriz Numpy y separa etiquetas en variables separadas

In [8]:
le = LabelEncoder()
for col in cc_apps.columns:
    if cc_apps[col].dtype=='object':
        cc_apps[col]=le.fit_transform(cc_apps[col])
cc_apps = cc_apps.drop([cc_apps.columns[10],cc_apps.columns[13]], axis=1)
cc_apps
cc_apps = cc_apps.values
X,y = cc_apps[:,0:13], cc_apps[:,13]

In [9]:
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(rescaledX,
                                                    y,
                                                    test_size=0.20,train_size=0.80,
                                                    random_state=42)
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)
print("Precisión del clasificador de regresión logística: ", logreg.score(X_test, y_test))
print(confusion_matrix(y_test, y_pred))
print("\n Ejemplos usados para entrenar TRAIN: ")
print("Ejemplos usados para test: TEST\n")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print('\n X_train: ',len(X_train))
print(X_train)
print('\n X_test: ',len(X_test))
print(X_test)
print('y_train: ',len(y_train))
print(y_train)
print('\n y_test: ',len(y_test))
print(y_test)

classifier = MLPClassifier(activation="relu",solver='adam', hidden_layer_sizes=(100,),max_iter=300)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print('\n Y_PREDICC: ',y_pred)
accuracy = accuracy_score(y_test, y_pred)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Datos estadísticos de las precisiones\n")
print('Media de las precisiones después de la validación cruzada: ', accuracies.mean())
print('Desviación estándar dentro de las precisiones: ', accuracies.std())
print('precisiones: ', accuracies)

Precisión del clasificador de regresión logística:  0.8188405797101449
[[60 10]
 [15 53]]

 Ejemplos usados para entrenar TRAIN: 
Ejemplos usados para test: TEST


 X_train:  552
[[1.000e+00 7.200e+01 1.100e+01 ... 1.000e+00 0.000e+00 8.090e+02]
 [1.000e+00 2.360e+02 5.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 7.800e+01 1.000e+00 ... 0.000e+00 2.000e+00 0.000e+00]
 ...
 [0.000e+00 3.800e+01 6.650e-01 ... 0.000e+00 0.000e+00 5.000e+00]
 [0.000e+00 7.300e+01 2.290e+00 ... 1.000e+00 0.000e+00 2.384e+03]
 [1.000e+00 2.400e+02 3.290e+00 ... 1.000e+00 2.000e+00 0.000e+00]]

 X_test:  138
[[0.00e+00 2.70e+02 1.05e+01 ... 1.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 3.37e+02 2.00e+01 ... 1.00e+00 0.00e+00 1.00e+03]
 [0.00e+00 1.59e+02 3.75e+00 ... 1.00e+00 0.00e+00 0.00e+00]
 ...
 [1.00e+00 3.04e+02 1.50e+00 ... 1.00e+00 0.00e+00 3.50e+02]
 [1.00e+00 1.94e+02 2.50e+00 ... 0.00e+00 0.00e+00 0.00e+00]
 [1.00e+00 4.80e+01 4.15e-01 ... 0.00e+00 0.00e+00 4.40e+01]]
y_train:  552
[0. 1. 0. 0.